name: Run API Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests pytest pytest-html
      - name: Run tests
        run: pytest api_tests/ --html=reports/report.html --self-contained-html
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: reports/report.html